name: Z
favicon: null
layout_spectrum: 0.7161232756916434
typography_spectrum: 0.7671360173262656
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.04007859202101827
  lightness: 0.42945000366307795
  saturation: 0.04942666389979422
  rhythmicContrast: 0.1846371591091156
purpose: []
